# Generated by Django 4.0.6 on 2023-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsOrMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID', models.IntegerField()),
                ('WhatIsIt', models.CharField(max_length=25)),
                ('SenderID', models.IntegerField()),
                ('SenderRole', models.CharField(max_length=25)),
                ('ContentData', models.CharField(max_length=750)),
                ('SendingDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
