# Generated by Django 4.0.6 on 2023-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsormessages',
            name='FinalSubmission',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
