# Generated by Django 4.0.6 on 2023-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_Admin', '0004_alter_reportsormessages_finalsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsormessages',
            name='FinalSubmission',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
