# Generated by Django 4.0.6 on 2023-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_Admin', '0006_remove_reportsormessages_finalsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderID', models.IntegerField()),
                ('ReceiverID', models.IntegerField()),
                ('ContentData', models.CharField(max_length=750)),
                ('SendingDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID', models.IntegerField()),
                ('SenderID', models.IntegerField()),
                ('SenderRole', models.CharField(max_length=25)),
                ('ContentData', models.CharField(max_length=750)),
                ('SendingDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
