# Generated by Django 4.0.6 on 2023-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_Admin', '0008_alter_allsuggestions_senderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsuggestions',
            name='SenderID',
            field=models.IntegerField(default=None),
        ),
    ]
