# Generated by Django 4.0.6 on 2023-02-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_Admin', '0009_alter_allsuggestions_senderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allsuggestions',
            name='SenderID',
        ),
    ]
