# Generated by Django 4.0.6 on 2023-02-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_Admin', '0010_remove_allsuggestions_senderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsuggestions',
            name='SenderID',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
