# Generated by Django 4.0.6 on 2023-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('FullName', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=30)),
                ('MobileNo', models.IntegerField()),
                ('Language', models.CharField(default=None, max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField(default=None)),
                ('State', models.CharField(max_length=25)),
                ('Country', models.CharField(max_length=25)),
                ('ProfilePick', models.ImageField(default=None, max_length=75, upload_to='client/')),
                ('Company', models.CharField(max_length=100)),
                ('EmploymentID', models.CharField(max_length=100)),
                ('As', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=100)),
                ('Level', models.IntegerField()),
                ('OfficeLocation', models.CharField(max_length=100)),
                ('SittingArea', models.CharField(max_length=100)),
                ('JoiningBeginningDate', models.DateTimeField(default=None, null=True)),
                ('JoiningEndingDate', models.DateTimeField(default=None, null=True)),
                ('Salary', models.IntegerField()),
                ('Contract', models.CharField(max_length=20)),
                ('CTC', models.CharField(max_length=250)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
