# Generated by Django 4.0.6 on 2023-02-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='JoiningBeginningDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='JoiningEndingDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Language',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ZipCode',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
