# Generated by Django 4.0.6 on 2023-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_HR', '0002_alter_employee_joiningbeginningdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='CompanyJoiningDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='CompanyLeavingDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
