# Generated by Django 4.0.6 on 2023-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_HR', '0003_employee_companyjoiningdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Contract',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
