# Generated by Django 4.0.6 on 2023-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_HR', '0004_alter_employee_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ProfilePick',
            field=models.ImageField(default=None, max_length=75, upload_to='employee/'),
        ),
    ]
