# Generated by Django 4.0.6 on 2023-01-30 17:20

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('FullName', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=30)),
                ('MobileNo', models.IntegerField()),
                ('Organization', models.CharField(max_length=30)),
                ('Language', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField()),
                ('State', models.CharField(max_length=25)),
                ('Country', models.CharField(max_length=25)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('ProfilePick', models.ImageField(default=None, max_length=75, upload_to='client/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.IntegerField()),
                ('HR', models.IntegerField(default=None, null=True)),
                ('ProjectManager', models.IntegerField(default=None, null=True)),
                ('Developer', models.IntegerField(default=None, null=True)),
                ('ProjectName', models.CharField(max_length=50)),
                ('ProjectSlug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='ProjectName')),
                ('ProgrammingLanguage', models.CharField(max_length=50)),
                ('FrontEnd', models.CharField(max_length=50)),
                ('BackEnd', models.CharField(max_length=50)),
                ('DataBase', models.CharField(max_length=50)),
                ('BeginningDate', models.DateTimeField(default=None, null=True)),
                ('EndingDate', models.DateTimeField(default=None, null=True)),
                ('StartingAmount', models.CharField(default=None, max_length=10)),
                ('EndingAmount', models.CharField(default=None, max_length=10)),
                ('SoftDiscription', models.CharField(max_length=350)),
                ('HardDiscription', models.CharField(default=None, max_length=500, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('ReportStatus', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
