# Generated by Django 4.0.6 on 2023-02-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='Admin',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
