# Generated by Django 4.0.6 on 2023-02-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_Client', '0002_projectinfo_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeveloperID', models.IntegerField(default=None, null=True)),
                ('ProjectInfosID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Client.projectinfo')),
            ],
        ),
    ]
