# Generated by Django 4.0.6 on 2023-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID', models.IntegerField()),
                ('ReceiverID', models.IntegerField(default=None, null=True)),
                ('ContentData', models.CharField(max_length=750)),
                ('SendingDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
