# Generated by Django 4.0.6 on 2023-03-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ProjectManager', '0002_alltasks_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltasks',
            name='GitHubLink',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='alltasks',
            name='OptionalMSG',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
    ]
