# Generated by Django 4.0.6 on 2023-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ProjectManager', '0003_alltasks_githublink_alltasks_optionalmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltasks',
            name='OptionalMSG',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
