# Generated by Django 4.0.6 on 2023-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ProjectManager', '0004_alter_alltasks_optionalmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltasks',
            name='TaskOver',
            field=models.BooleanField(default=False),
        ),
    ]
