# Generated by Django 4.0.6 on 2023-03-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ProjectManager', '0005_alltasks_taskover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alltasks',
            old_name='TaskOver',
            new_name='IsTaskFinished',
        ),
    ]
